/* Autocomplete for the meet location field.

   A curated list of major world cities, weighted towards places that host
   athletics — it is a convenience for typing, not a validation list, so any
   value is still accepted. Format is exactly what the field stores:
   "City, Country". */
export const CITIES = [
  // North America
  'New York, United States', 'Brooklyn, United States', 'Los Angeles, United States',
  'Chicago, United States', 'Houston, United States', 'Phoenix, United States',
  'Philadelphia, United States', 'San Antonio, United States', 'San Diego, United States',
  'Dallas, United States', 'Austin, United States', 'San Jose, United States',
  'Jacksonville, United States', 'Fort Worth, United States', 'Columbus, United States',
  'Charlotte, United States', 'Indianapolis, United States', 'San Francisco, United States',
  'Seattle, United States', 'Denver, United States', 'Boston, United States',
  'Nashville, United States', 'Detroit, United States', 'Portland, United States',
  'Las Vegas, United States', 'Memphis, United States', 'Louisville, United States',
  'Baltimore, United States', 'Milwaukee, United States', 'Albuquerque, United States',
  'Tucson, United States', 'Sacramento, United States', 'Kansas City, United States',
  'Atlanta, United States', 'Miami, United States', 'Raleigh, United States',
  'Omaha, United States', 'Minneapolis, United States', 'Tampa, United States',
  'New Orleans, United States', 'Cleveland, United States', 'Honolulu, United States',
  'Pittsburgh, United States', 'Cincinnati, United States', 'St. Louis, United States',
  'Orlando, United States', 'Salt Lake City, United States', 'Eugene, United States',
  'Des Moines, United States', 'Boise, United States', 'Buffalo, United States',
  'Toronto, Canada', 'Montreal, Canada', 'Vancouver, Canada', 'Calgary, Canada',
  'Edmonton, Canada', 'Ottawa, Canada', 'Quebec City, Canada', 'Winnipeg, Canada',
  'Hamilton, Canada', 'Halifax, Canada',
  'Mexico City, Mexico', 'Guadalajara, Mexico', 'Monterrey, Mexico', 'Puebla, Mexico',
  'Tijuana, Mexico', 'Cancún, Mexico', 'Mérida, Mexico',
  'Havana, Cuba', 'Kingston, Jamaica', 'Santo Domingo, Dominican Republic',
  'San Juan, Puerto Rico', 'Port-au-Prince, Haiti', 'Nassau, Bahamas',
  'Panama City, Panama', 'San José, Costa Rica', 'Guatemala City, Guatemala',
  'Tegucigalpa, Honduras', 'Managua, Nicaragua', 'San Salvador, El Salvador',
  'Bridgetown, Barbados', 'Port of Spain, Trinidad and Tobago',

  // South America
  'São Paulo, Brazil', 'Rio de Janeiro, Brazil', 'Brasília, Brazil', 'Salvador, Brazil',
  'Fortaleza, Brazil', 'Belo Horizonte, Brazil', 'Curitiba, Brazil', 'Porto Alegre, Brazil',
  'Recife, Brazil', 'Manaus, Brazil',
  'Buenos Aires, Argentina', 'Córdoba, Argentina', 'Rosario, Argentina', 'Mendoza, Argentina',
  'Santiago, Chile', 'Valparaíso, Chile', 'Lima, Peru', 'Arequipa, Peru',
  'Bogotá, Colombia', 'Medellín, Colombia', 'Cali, Colombia', 'Cartagena, Colombia',
  'Caracas, Venezuela', 'Quito, Ecuador', 'Guayaquil, Ecuador', 'La Paz, Bolivia',
  'Montevideo, Uruguay', 'Asunción, Paraguay', 'Georgetown, Guyana',

  // Europe
  'London, United Kingdom', 'Manchester, United Kingdom', 'Birmingham, United Kingdom',
  'Liverpool, United Kingdom', 'Leeds, United Kingdom', 'Glasgow, United Kingdom',
  'Edinburgh, United Kingdom', 'Sheffield, United Kingdom', 'Bristol, United Kingdom',
  'Cardiff, United Kingdom', 'Belfast, United Kingdom', 'Newcastle, United Kingdom',
  'Dublin, Ireland', 'Cork, Ireland',
  'Paris, France', 'Marseille, France', 'Lyon, France', 'Toulouse, France',
  'Nice, France', 'Nantes, France', 'Bordeaux, France', 'Lille, France',
  'Berlin, Germany', 'Munich, Germany', 'Hamburg, Germany', 'Cologne, Germany',
  'Frankfurt, Germany', 'Stuttgart, Germany', 'Düsseldorf, Germany', 'Leipzig, Germany',
  'Dortmund, Germany', 'Essen, Germany',
  'Madrid, Spain', 'Barcelona, Spain', 'Valencia, Spain', 'Seville, Spain',
  'Bilbao, Spain', 'Málaga, Spain', 'Zaragoza, Spain',
  'Rome, Italy', 'Milan, Italy', 'Naples, Italy', 'Turin, Italy',
  'Florence, Italy', 'Bologna, Italy', 'Venice, Italy', 'Palermo, Italy',
  'Lisbon, Portugal', 'Porto, Portugal',
  'Amsterdam, Netherlands', 'Rotterdam, Netherlands', 'The Hague, Netherlands',
  'Utrecht, Netherlands', 'Eindhoven, Netherlands',
  'Brussels, Belgium', 'Antwerp, Belgium', 'Ghent, Belgium',
  'Zurich, Switzerland', 'Geneva, Switzerland', 'Basel, Switzerland', 'Lausanne, Switzerland',
  'Bern, Switzerland',
  'Vienna, Austria', 'Salzburg, Austria', 'Graz, Austria',
  'Stockholm, Sweden', 'Gothenburg, Sweden', 'Malmö, Sweden',
  'Oslo, Norway', 'Bergen, Norway', 'Copenhagen, Denmark', 'Aarhus, Denmark',
  'Helsinki, Finland', 'Reykjavík, Iceland',
  'Warsaw, Poland', 'Kraków, Poland', 'Łódź, Poland', 'Wrocław, Poland', 'Gdańsk, Poland',
  'Prague, Czechia', 'Brno, Czechia', 'Bratislava, Slovakia',
  'Budapest, Hungary', 'Bucharest, Romania', 'Cluj-Napoca, Romania',
  'Sofia, Bulgaria', 'Belgrade, Serbia', 'Zagreb, Croatia', 'Split, Croatia',
  'Ljubljana, Slovenia', 'Sarajevo, Bosnia and Herzegovina', 'Skopje, North Macedonia',
  'Tirana, Albania', 'Podgorica, Montenegro', 'Pristina, Kosovo',
  'Athens, Greece', 'Thessaloniki, Greece',
  'Istanbul, Türkiye', 'Ankara, Türkiye', 'İzmir, Türkiye', 'Antalya, Türkiye',
  'Kyiv, Ukraine', 'Lviv, Ukraine', 'Odesa, Ukraine',
  'Moscow, Russia', 'Saint Petersburg, Russia', 'Kazan, Russia', 'Novosibirsk, Russia',
  'Minsk, Belarus', 'Riga, Latvia', 'Vilnius, Lithuania', 'Tallinn, Estonia',
  'Luxembourg, Luxembourg', 'Monaco, Monaco', 'Valletta, Malta', 'Nicosia, Cyprus',

  // Africa
  'Cairo, Egypt', 'Alexandria, Egypt', 'Giza, Egypt',
  'Lagos, Nigeria', 'Abuja, Nigeria', 'Kano, Nigeria', 'Ibadan, Nigeria',
  'Nairobi, Kenya', 'Mombasa, Kenya', 'Eldoret, Kenya', 'Kisumu, Kenya',
  'Addis Ababa, Ethiopia', 'Dire Dawa, Ethiopia',
  'Johannesburg, South Africa', 'Cape Town, South Africa', 'Durban, South Africa',
  'Pretoria, South Africa', 'Port Elizabeth, South Africa',
  'Casablanca, Morocco', 'Rabat, Morocco', 'Marrakesh, Morocco', 'Tangier, Morocco',
  'Algiers, Algeria', 'Oran, Algeria', 'Tunis, Tunisia', 'Tripoli, Libya',
  'Accra, Ghana', 'Kumasi, Ghana', 'Abidjan, Côte d’Ivoire', 'Yamoussoukro, Côte d’Ivoire',
  'Dakar, Senegal', 'Bamako, Mali', 'Ouagadougou, Burkina Faso', 'Conakry, Guinea',
  'Freetown, Sierra Leone', 'Monrovia, Liberia', 'Lomé, Togo', 'Cotonou, Benin',
  'Douala, Cameroon', 'Yaoundé, Cameroon', 'Libreville, Gabon',
  'Kinshasa, DR Congo', 'Lubumbashi, DR Congo', 'Brazzaville, Republic of the Congo',
  'Luanda, Angola', 'Windhoek, Namibia', 'Gaborone, Botswana', 'Harare, Zimbabwe',
  'Lusaka, Zambia', 'Maputo, Mozambique', 'Lilongwe, Malawi', 'Antananarivo, Madagascar',
  'Dar es Salaam, Tanzania', 'Dodoma, Tanzania', 'Kampala, Uganda', 'Kigali, Rwanda',
  'Bujumbura, Burundi', 'Mogadishu, Somalia', 'Khartoum, Sudan', 'Asmara, Eritrea',
  'Djibouti, Djibouti', 'Port Louis, Mauritius',

  // Middle East & Central Asia
  'Dubai, United Arab Emirates', 'Abu Dhabi, United Arab Emirates', 'Sharjah, United Arab Emirates',
  'Doha, Qatar', 'Kuwait City, Kuwait', 'Manama, Bahrain', 'Muscat, Oman',
  'Riyadh, Saudi Arabia', 'Jeddah, Saudi Arabia', 'Mecca, Saudi Arabia',
  'Tel Aviv, Israel', 'Jerusalem, Israel', 'Haifa, Israel',
  'Amman, Jordan', 'Beirut, Lebanon', 'Damascus, Syria', 'Baghdad, Iraq', 'Erbil, Iraq',
  'Tehran, Iran', 'Mashhad, Iran', 'Isfahan, Iran',
  'Kabul, Afghanistan', 'Tashkent, Uzbekistan', 'Almaty, Kazakhstan', 'Astana, Kazakhstan',
  'Bishkek, Kyrgyzstan', 'Dushanbe, Tajikistan', 'Ashgabat, Turkmenistan',
  'Baku, Azerbaijan', 'Tbilisi, Georgia', 'Yerevan, Armenia',

  // Asia
  'Tokyo, Japan', 'Osaka, Japan', 'Yokohama, Japan', 'Nagoya, Japan', 'Sapporo, Japan',
  'Fukuoka, Japan', 'Kyoto, Japan', 'Kobe, Japan', 'Hiroshima, Japan',
  'Seoul, South Korea', 'Busan, South Korea', 'Incheon, South Korea', 'Daegu, South Korea',
  'Beijing, China', 'Shanghai, China', 'Guangzhou, China', 'Shenzhen, China',
  'Chengdu, China', 'Chongqing, China', 'Tianjin, China', 'Wuhan, China',
  'Xi’an, China', 'Hangzhou, China', 'Nanjing, China', 'Shenyang, China',
  'Hong Kong, Hong Kong', 'Macau, Macau', 'Taipei, Taiwan', 'Kaohsiung, Taiwan',
  'Singapore, Singapore', 'Kuala Lumpur, Malaysia', 'George Town, Malaysia',
  'Bangkok, Thailand', 'Chiang Mai, Thailand', 'Phuket, Thailand',
  'Jakarta, Indonesia', 'Surabaya, Indonesia', 'Bandung, Indonesia', 'Bali, Indonesia',
  'Manila, Philippines', 'Cebu City, Philippines', 'Quezon City, Philippines',
  'Hanoi, Vietnam', 'Ho Chi Minh City, Vietnam', 'Da Nang, Vietnam',
  'Phnom Penh, Cambodia', 'Vientiane, Laos', 'Yangon, Myanmar', 'Naypyidaw, Myanmar',
  'Mumbai, India', 'Delhi, India', 'Bengaluru, India', 'Hyderabad, India',
  'Chennai, India', 'Kolkata, India', 'Pune, India', 'Ahmedabad, India',
  'Jaipur, India', 'Surat, India', 'Lucknow, India', 'Chandigarh, India',
  'Karachi, Pakistan', 'Lahore, Pakistan', 'Islamabad, Pakistan', 'Faisalabad, Pakistan',
  'Dhaka, Bangladesh', 'Chittagong, Bangladesh', 'Kathmandu, Nepal', 'Colombo, Sri Lanka',
  'Thimphu, Bhutan', 'Malé, Maldives', 'Ulaanbaatar, Mongolia',

  // Oceania
  'Sydney, Australia', 'Melbourne, Australia', 'Brisbane, Australia', 'Perth, Australia',
  'Adelaide, Australia', 'Canberra, Australia', 'Gold Coast, Australia', 'Hobart, Australia',
  'Auckland, New Zealand', 'Wellington, New Zealand', 'Christchurch, New Zealand',
  'Suva, Fiji', 'Port Moresby, Papua New Guinea', 'Nukuʻalofa, Tonga', 'Apia, Samoa',
];
